### ISSUE TITLE
Parse error when empty response

### ISSUE THREAD

**Issue by apriljunge** [derhuerst/seebruecke-events-calendar-feed#7]
I don't know exactly what is the right solution for my problem. I use the [ICSx5 app for Android](https://icsx5.bitfire.at/) to subscribe to the calendar for a local group. If there are no future events for this local group, then this webapp returns a completely empty file, causing an error in my app: _Couldn't parse iCalendar._

To figure out what the correct behavior would be, I tried to understand [the specification](https://datatracker.ietf.org/doc/html/rfc5545#section-3.4) and as it says [on stackoverflow](https://stackoverflow.com/questions/67681002/what-are-the-minimum-requirements-for-an-ics-file), I think the file should contain at least _BEGIN:VCALENDAR_ and _END:CALENDAR_ to be valid.

I think that you could either just return such minimal ics file (then the question would be if this should rather be done by the [ics-service](https://github.com/derhuerst/ics-service)) or you could also return n past events so that no error occurs for local groups that have already done events.

What do you think is the right solution in this case?

**Comment by derhuerst** [comment]
related: https://github.com/adamgibbons/ics/pull/148

**Comment by derhuerst** [comment]
> I think that you could either just return such minimal ics file (then the question would be if this should rather be done by the [ics-service](https://github.com/derhuerst/ics-service)) or you could also return n past events so that no error occurs for local groups that have already done events.

Yes, either in `ics-service` or even in the underlying `ics`.

PR welcome!
